# AUTOGENERATED FROM 'app/queries/meeting/get_meeting_by_url_code.edgeql' WITH:
#     $ edgedb-py --dir app/queries/meeting --no-skip-pydantic-validation


from __future__ import annotations
import dataclasses
import edgedb
import uuid


@dataclasses.dataclass
class GetMeetingByUrlCodeResult:
    id: uuid.UUID
    url_code: str


async def get_meeting_by_url_code(
    executor: edgedb.AsyncIOExecutor,
    *,
    url_code: str,
) -> GetMeetingByUrlCodeResult | None:
    return await executor.query_single(
        """\
        with
            url_code := <str>$url_code,
        select Meeting { url_code }
        filter .url_code = url_code
        limit 1\
        """,
        url_code=url_code,
    )
